name: shoko
description: Shoko Anime Server on Debian 13 (Trixie)
category: media
version: 5.1.0
build_version: 1
base_os: debian-13
architecture: amd64
maintainer: Deroy2112 <81692934+Deroy2112@users.noreply.github.com>

resources:
  memory_min: 1024
  memory_recommended: 2048
  disk_min: 5G
  disk_recommended: 10G
  cores: 2

ports:
  - port: 8111
    description: Web UI

paths:
  - path: /root/.shoko
    description: Configuration & database
  - path: /anime
    description: Anime library (mount point)

quick_start: |
  Web UI: http://<IP>:8111
  AniDB account required
  Mount anime folder as bind mount
