name: nginx
description: Nginx webserver on Debian 13 (Trixie)
category: network
version: 1.26.0
build_version: 1
base_os: debian-13
architecture: amd64
maintainer: Deroy2112 <81692934+Deroy2112@users.noreply.github.com>

resources:
  memory_min: 256
  memory_recommended: 512
  disk_min: 2G
  disk_recommended: 5G
  cores: 1

ports:
  - port: 80
    description: HTTP
  - port: 443
    description: HTTPS

paths:
  - path: /etc/nginx
    description: Konfiguration
  - path: /var/www/html
    description: Web Root
  - path: /var/log/nginx
    description: Logs

quick_start: |
  Web Server: http://<IP>
  Config: /etc/nginx/nginx.conf
  Test: nginx -t
  Reload: systemctl reload nginx
