name: nginx
description: Nginx webserver on Debian 13 (Trixie)
version: 1.26.0
build_version: 1
base_os: debian-13
architecture: amd64
maintainer: Deroy2112 <81692934+Deroy2112@users.noreply.github.com>

resources:
  memory_min: 256
  memory_recommended: 512
  disk_min: 2G
  disk_recommended: 5G
  cores: 1
